<?php

namespace Tests\Unit;

use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use GuzzleHttp\Psr7\Response;
use GuzzleHttp\Psr7\Uri;
use RolfHaug\FrontSms\Exceptions\Front\InvalidApiRequest;
use RolfHaug\FrontSms\FrontClient;
use RolfHaug\FrontSms\FrontMessage;
use Tests\TestCase;

class FrontClientTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app['config']->set('front-sms.serviceId', 1337);
    }

    /** @test */
    public function it_sends_sms_to_correct_url_with_correct_payload_and_updates_the_message_orig_id()
    {
        $sms = factory(FrontMessage::class)->create(['price' => 100]);
        $origId = 1234;

        $middleware = $this->pushMessageAndReturnMiddleware($sms, ['errorcode' => 0, 'id' => $origId, 'description' => 'OK']);

        /** @var Uri $uri */
        $uri = $middleware['request']->getUri();

        $this->assertEquals('https', $uri->getScheme());
        $this->assertEquals('www.pling.as', $uri->getHost());
        $this->assertEquals('/psk/push.php', $uri->getPath());
        $this->assertEmpty($uri->getQuery());

        // Request Payload
        $options = $middleware['options'];

        // Keys are sent
        $this->assertArrayHasKey('serviceid', $options, 'API Request is missing required data');
        $this->assertArrayHasKey('fromid', $options, 'API Request is missing required data');
        $this->assertArrayHasKey('phoneno', $options, 'API Request is missing required data');
        $this->assertArrayHasKey('txt', $options, 'API Request is missing required data');
        $this->assertArrayHasKey('price', $options, 'API Request is missing required data');
        $this->assertArrayHasKey('unicode', $options, 'API Request is missing required data');

        // Data are mapped correctly
        $this->assertEquals(config('front-sms.serviceId'), $options['serviceid']);
        $this->assertEquals($sms->from, $options['fromid']);
        $this->assertEquals($sms->to, $options['phoneno']);
        $this->assertEquals($sms->message, $options['txt']);
        $this->assertEquals($sms->price, $options['price']);
        $this->assertEquals($sms->isUnicode(), $options['unicode']);

        $this->assertEquals($origId, $sms->fresh()->origid);
    }

    /** @test */
    public function it_throws_invalid_api_request_exception_if_error_code_is_greater_than_0()
    {
        $this->expectException(InvalidApiRequest::class);
        $this->expectExceptionMessageRegExp('/Something happened/');

        $sms = factory(FrontMessage::class)->create();

        $this->pushMessageAndReturnMiddleware($sms, ['errorcode' => 1, 'id' => 0, 'description' => 'Something happened']);
    }

    /** @test */
    public function it_defaults_to_not_using_unicode()
    {
        $sms = factory(FrontMessage::class)->create(['message' => 'Not a unicode message']);
        $this->assertFalse($sms->isUnicode());

        $middleware = $this->pushMessageAndReturnMiddleware($sms);
        $this->assertEquals(false, $middleware['options']['unicode'], 'Unicode field was not set properly');
    }

    /** @test */
    public function it_sets_unicode_field_to_true_if_message_is_unicode()
    {
        $sms = factory(FrontMessage::class)->create(['message' => 'Unicode Message 💪']);
        $this->assertTrue($sms->isUnicode());

        $middleware = $this->pushMessageAndReturnMiddleware($sms);

        $this->assertEquals(true, $middleware['options']['unicode'], 'Unicode field was not set properly');
    }

    protected function pushMessageAndReturnMiddleware(FrontMessage $sms, $response = null)
    {
        if (! $response) {
            $response = ['errorcode' => 0, 'id' => 1, 'description' => 'OK'];
        }

        $mock = new MockHandler([
            new Response(200, [], json_encode($response))
        ]);

        $container = [];
        $history = Middleware::history($container);
        $handlerStack = HandlerStack::create($mock);
        $handlerStack->push($history);

        $client = new Client(['handler' => $handlerStack]);

        (new FrontClient($client))->push($sms);

        return $container[0];
    }
}
